apiVersion: v1
kind: Service
metadata:
  name: criar-reserva-service
spec:
  type: NodePort 
  ports:
    - port: 7000       # Porta interna no cluster
      targetPort: 7000 # Porta no container
      nodePort: 30001   # Porta exposta no host
  selector:
    app: criar-reserva
