apiVersion: apps/v1
kind: Deployment
metadata:
  name: operador-base-usuarios
  labels:
    app: operador-base-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operador-base-usuarios
  template:
    metadata:
      labels:
        app: operador-base-usuarios
    spec:
      containers:
      - name: operador-base-usuarios
        image: caiomc03rx/operador-base-usuarios:latest
        ports:
        - containerPort: 6001
        env:
        - name: NODE_ENV
          value: "production"
