apiVersion: v1
kind: Service
metadata:
  name: operador-base-usuarios-service
spec:
  type: NodePort 
  ports:
    - port: 6001       # Porta interna no cluster
      targetPort: 6001 # Porta no container
      nodePort: 30402   # Porta exposta no host
  selector:
    app: operador-base-usuarios
