apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancela-reserva
  labels:
    app: cancela-reserva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cancela-reserva
  template:
    metadata:
      labels:
        app: cancela-reserva
    spec:
      containers:
      - name: cancela-reserva
        image: caiomc03rx/cancela-reserva:latest
        ports:
        - containerPort: 7004
        env:
        - name: NODE_ENV
          value: "production"
