apiVersion: v1
kind: Service
metadata:
  name: cancela-reserva-service
spec:
  type: NodePort 
  ports:
    - port: 7004       # Porta interna no cluster
      targetPort: 7004 # Porta no container
      nodePort: 30004   # Porta exposta no host
  selector:
    app: cancela-reserva
