apiVersion: v1
kind: Service
metadata:
  name: consulta-user-reservas-service
spec:
  type: NodePort 
  ports:
    - port: 7003       # Porta interna no cluster
      targetPort: 7003 # Porta no container
      nodePort: 30003   # Porta exposta no host
  selector:
    app: consulta-user-reservas
