apiVersion: v1
kind: Service
metadata:
  name: operador-base-reservas-service
spec:
  type: NodePort 
  ports:
    - port: 7001       # Porta interna no cluster
      targetPort: 7001 # Porta no container
      nodePort: 30401   # Porta exposta no host
  selector:
    app: operador-base-reservas
