apiVersion: apps/v1
kind: Deployment
metadata:
  name: criar-usuarios
  labels:
    app: criar-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criar-usuarios
  template:
    metadata:
      labels:
        app: criar-usuarios
    spec:
      containers:
      - name: criar-usuarios
        image: caiomc03rx/criar-usuarios:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
