apiVersion: v1
kind: Service
metadata:
  name: criar-usuarios-service
spec:
  type: NodePort 
  ports:
    - port: 4000       # Porta interna no cluster
      targetPort: 4000 # Porta no container
      nodePort: 30400   # Porta exposta no host
  selector:
    app: criar-usuarios
